'use strict';
/**
 * Discord Webhook — delivers completed episodes to the configured server channel.
 *
 * WEBHOOK_URL : full webhook URL from Discord channel settings.
 *               Also accepts DISCORD_WEBHOOK_URL as a fallback alias.
 *
 * Each completed episode is posted as a rich embed containing:
 *   - Episode title
 *   - Caption + hashtags (as generated by the director AI)
 *   - The actual video file as an attachment (downloaded from Cloudinary first)
 */
const axios      = require('axios');
const FormData   = require('form-data');
const config     = require('./config');

/**
 * Post a completed episode to the Discord webhook, downloading the video first
 * so Discord receives the actual file instead of a link.
 *
 * @param {object} opts
 * @param {string} opts.videoUrl   Cloudinary URL of the final compiled episode
 * @param {string} opts.title      Full episode title (Show — S01E01 — Episode Name)
 * @param {string} opts.caption    AI-generated caption / post copy
 * @param {string} opts.hashtags   Hashtag string to post alongside the caption
 * @returns {string|null}          videoUrl on success, null if webhook not configured
 */
async function postEpisode({ videoUrl, title, caption, hashtags }) {
  const webhookUrl = config.discordWebhookUrl;
  if (!webhookUrl) {
    console.warn('[Discord] WEBHOOK_URL not configured — skipping Discord post');
    return null;
  }

  const captionBody  = (caption   || '').slice(0, 3800);
  const hashtagBody  = (hashtags  || '').slice(0, 200);
  const description  = [captionBody, hashtagBody].filter(Boolean).join('\n\n');

  // Download the video from Cloudinary so we can attach the actual file.
  // Discord webhook file uploads are capped (10MB standard / 50MB with a Level 2
  // server boost — see config.discordMaxUploadBytes). If the file is over that
  // limit, or the download fails, we skip the attachment and fall back to a
  // link embed instead — that still counts as a successful post so the job
  // completes and the pipeline moves on to the next episode.
  const maxUploadBytes = config.discordMaxUploadBytes;
  let videoBuffer = null;
  let fileName = `episode_${Date.now()}.mp4`;
  let skipReason = null;

  try {
    // HEAD first so an oversized file is never fully downloaded into memory
    // just to be thrown away.
    const headResp = await axios.head(videoUrl, { timeout: 20000 }).catch(() => null);
    const declaredLength = parseInt(headResp?.headers?.['content-length'] || '', 10);

    if (Number.isFinite(declaredLength) && declaredLength > maxUploadBytes) {
      skipReason = `video is ${(declaredLength / (1024 * 1024)).toFixed(1)}MB, ` +
        `over the ${(maxUploadBytes / (1024 * 1024)).toFixed(0)}MB Discord upload limit`;
    } else {
      const dlResp = await axios.get(videoUrl, { responseType: 'arraybuffer', timeout: 180000 });
      const buf = Buffer.from(dlResp.data);

      if (buf.length > maxUploadBytes) {
        skipReason = `video is ${(buf.length / (1024 * 1024)).toFixed(1)}MB, ` +
          `over the ${(maxUploadBytes / (1024 * 1024)).toFixed(0)}MB Discord upload limit`;
      } else {
        videoBuffer = buf;
        // Try to extract a filename from the URL path
        const urlPath = new URL(videoUrl).pathname;
        const lastSeg = urlPath.split('/').pop();
        if (lastSeg && lastSeg.includes('.')) fileName = lastSeg;
        console.log(`[Discord] Downloaded video for attachment: ${videoBuffer.length} bytes`);
      }
    }
  } catch (dlErr) {
    skipReason = `download failed: ${dlErr.message}`;
  }

  if (skipReason) {
    console.warn(`[Discord] Skipping file attachment — falling back to link embed (${skipReason})`);
  }

  const payload = {
    embeds: [
      {
        title:       title.slice(0, 256),
        description: description || '*No caption generated.*',
        color:       0x7B2FBE,
        fields: videoBuffer
          ? []
          : [{ name: '📺 Watch / Download', value: videoUrl.slice(0, 1024), inline: false }],
        footer:    { text: 'StreamVerse Studios' },
        timestamp: new Date().toISOString(),
      },
    ],
  };

  try {
    if (videoBuffer) {
      // Send the video as a file attachment via multipart form data.
      const form = new FormData();
      form.append('payload_json', JSON.stringify(payload));
      form.append('file', videoBuffer, { filename: fileName, contentType: 'video/mp4' });

      const resp = await axios.post(webhookUrl, form, {
        headers: { ...form.getHeaders() },
        timeout: 30000,
      });
      console.log(`[Discord] Episode posted with video attachment (HTTP ${resp.status}): ${title}`);
    } else {
      // Fallback: just send the embed with the link
      const resp = await axios.post(webhookUrl, payload, {
        headers: { 'Content-Type': 'application/json' },
        timeout: 20000,
      });
      console.log(`[Discord] Episode posted with link (HTTP ${resp.status}): ${title}`);
    }
    return videoUrl;
  } catch (err) {
    const detail = err.response?.data ? JSON.stringify(err.response.data).slice(0, 300) : err.message;
    throw new Error(`[Discord] Webhook post failed: ${detail}`);
  }
}

/**
 * Send a plain-text announcement to the Discord webhook (series premiere, finale, etc.)
 *
 * @param {string} message  Plain text — kept under Discord's 2000-char content limit.
 */
async function postAnnouncement(message) {
  const webhookUrl = config.discordWebhookUrl;
  if (!webhookUrl) {
    console.warn('[Discord] WEBHOOK_URL not configured — skipping announcement');
    return;
  }
  try {
    await axios.post(
      webhookUrl,
      { content: String(message).slice(0, 2000) },
      { headers: { 'Content-Type': 'application/json' }, timeout: 10000 }
    );
    console.log('[Discord] Announcement sent');
  } catch (err) {
    console.warn('[Discord] Announcement failed:', err.message);
  }
}

module.exports = { postEpisode, postAnnouncement };
